### PR TITLE
Introduce a command line interface.

### PR DESCRIPTION
**Pull request by greenhal**
This commit introduces a command line interface (CLI) to facilitate the execution of the benchmark independently of a Streamlit application. CLI commands have been developed for the following clients: Milvus, pgvector, Redis, Weaviate Cloud, and Zilliz Cloud. The README.md file has been revised to include instructions on running the benchmark and integrating the command line option with new or existing clients.

This commit also has some general cleanups as well.

Co-authored-by: Tyler House [tahouse@users.noreply.github.com](mailto:tahouse@users.noreply.github.com)

### CODE REVIEW

**Comment by greenhal** [comment]
/ #330

**Comment by alwayslove2013** [comment]
@greenhal I am absolutely thrilled and deeply grateful for your incredible contribution to our project! The new CLI support you developed is going to make a huge difference for our users, and I can't wait to get it integrated and released.

Please know that I'm committed to reviewing your pull request as soon as possible. I'll give it my full attention and care to make sure it gets merged smoothly. 

Again, thank you from the bottom of my heart. I'm proud and humbled to have you as part of our community. Looking forward to many more amazing collaborations ahead!

**Comment by greenhal** [comment]
Any questions on this PR?

**Review by alwayslove2013 — APPROVED** [review]
First and foremost, I would like to express my sincere gratitude for submitting this extensive PR. The changes you have proposed cover a wide range of functionality and complexity, and our team has spent a significant amount of time carefully reviewing and testing it. Thank you for your patience as we take the time to properly evaluate each and every contribution made by our community.

After a thorough evaluation, we have determined that your PR aligns with our design goals and coding standards, and we have decided to merge your changes. This merge will undoubtedly enhance the functionality and user experience of our project. Once again, thank you for your outstanding contribution, and we hope that you will continue to support and participate in the development of our project.

**Pull request merged**
