### PR TITLE
Add rate runner

### PR DESCRIPTION
**Pull request by XuanYang-cn**

### CODE REVIEW

**Comment by XuanYang-cn** [comment]
Result = [(0, 607.2989, np.float64(0.0035)), (50, 419.5706, np.float64(0.4804)), (100, 2274.2178, np.float64(0.8904))]

**Comment by wahajali** [comment]
@XuanYang-cn This is interesting, but I don't see the `ReadWriteRunner` being used and neither did I find any documentation around it, can you please guide what this is intended for?

**Comment by alwayslove2013** [comment]
@wahajali we are currently in the process of designing and developing the streaming case. 

Our primary focus is testing vector database performance in real-time insertion and querying. Please note that this pull request is just one component of the overall project.

**Comment by wahajali** [comment]
@alwayslove2013 Thank you for the clarification. This sounds like a very exciting use case, and I’m particularly interested in real-time insertion and querying scenarios. If possible, I’d love to know if there’s an estimated timeline for this or a chance to preview any early work via some branch. I completely understand that this is a work in progress and part of a larger effort — just very eager to follow along and explore!

**Pull request merged**
