### PR TITLE
Added pgvectorscale client

### PR DESCRIPTION
**Pull request by Sheharyar570**
Added pgvectorscale client. I've tested the integration of pgvectorscale. I'm attaching the screenshots here.

Screenshot from 2024-07-31 18-15-55
Screenshot from 2024-07-31 17-47-10

### CODE REVIEW

**Comment by alwayslove2013** [comment]
@Sheharyar570 Wow! I can't wait to get this approved! But it looks like there's still a conflict with pr: #353 .

**Comment by Sheharyar570** [comment]
@alwayslove2013 I've resolved the conflict and updated the PR.You can review, Thanks

**Review by alwayslove2013 — APPROVED** [review]

**Pull request merged**
